# Generated by Django 4.2.13 on 2024-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyGenerationAuthgroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'key_generation_authgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyGenerationAuthpermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'key_generation_authpermission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyGenerationAuthuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'key_generation_authuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyGenerationDjangocontenttype',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'key_generation_djangocontenttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyGenerationDjangomigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'key_generation_djangomigrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyGenerationDjangosession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'key_generation_djangosession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyGenerationPeople',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('фио', models.CharField(blank=True, db_column='ФИО', max_length=30, null=True)),
                ('дата_рождения', models.DateField(blank=True, db_column='Дата рождения', null=True)),
                ('пол', models.CharField(blank=True, db_column='Пол', max_length=10, null=True)),
                ('страна', models.CharField(blank=True, db_column='Страна', max_length=10, null=True)),
                ('город', models.CharField(blank=True, db_column='Город', max_length=15, null=True)),
                ('домашний_адрес', models.CharField(blank=True, db_column='Домашний адрес', max_length=50, null=True)),
                ('номер_телефона', models.CharField(blank=True, db_column='Номер телефона', max_length=12, null=True)),
            ],
            options={
                'db_table': 'key_generation_people',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': False},
        ),
    ]
