# Generated by Django 4.2.13 on 2024-05-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_generation', '0002_keygenerationauthgroup_keygenerationauthpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authgroup',
            table='auth_group',
        ),
        migrations.AlterModelTable(
            name='authgrouppermissions',
            table='auth_group_permissions',
        ),
        migrations.AlterModelTable(
            name='authpermission',
            table='auth_permission',
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='auth_user',
        ),
        migrations.AlterModelTable(
            name='authusergroups',
            table='auth_user_groups',
        ),
        migrations.AlterModelTable(
            name='authuseruserpermissions',
            table='auth_user_user_permissions',
        ),
        migrations.AlterModelTable(
            name='djangoadminlog',
            table='django_admin_log',
        ),
        migrations.AlterModelTable(
            name='djangocontenttype',
            table='django_content_type',
        ),
        migrations.AlterModelTable(
            name='djangomigrations',
            table='django_migrations',
        ),
        migrations.AlterModelTable(
            name='djangosession',
            table='django_session',
        ),
        migrations.AlterModelTable(
            name='people',
            table='people',
        ),
    ]
